title: ~/Dileep/Blog$
author: Dileep Kushwaha
email: dileepkushwaha@hotmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A personal blog about technical things I find useful. Also, random ramblings and rants...
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"
  #date_format: "%d %-b, %Y"

  #disqus:
  #  shortname: dileepkushwaha-github-io-blogbitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/dileepkush
      icon: twitter-square
      color: cyan
    - url: https://github.com/dileepkushwaha
      icon: github-square
      color: purple
    - url: https://fosstodon.org/@dileepkushwaha
      icon: mastodon
      color: orange
    - url: https://steamcommunity.com/id/roo00t
      icon: steam-square
      color: green
    - url: https://www.linkedin.com/in/kushwahadileep/
      icon: linkedin
      color: purple
    - url: https://dileepkushwaha.github.io/resume/
      icon: font-awesome
      color: teal

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jemoji

 # jemoji settings
emoji:
  src: "https://github.githubassets.com/images/icons/"
